### ISSUE TITLE
AWS key 관련

### ISSUE THREAD

**Issue by YEEN6** [kookmin-sw/2018-cap1-9#14]
@daianaludice 
key를 깃허브 레포지토리에 올리는 건 보안적인 측면에서 위험하다고 생각하는데 내리는 게 어떨까?
깃 레포에 두고 계속 쓰고싶은거면 gitignore에 추가를 하는 게 좋을 것 같아!!

**Comment by daianaludice** [comment]
그럼 보안적인 측면에서 위험함으로 삭제한다고 커밋 작성해서 삭제하도록 할게!

**Comment by daianaludice** [comment]
AWS key 삭제 완료
