### ISSUE TITLE
중간평가 발표자료 및 프레젠테이션 준비

### ISSUE THREAD

**Issue by YEEN6** [kookmin-sw/2018-cap1-9#18]
1. 일시: 2018년 4월 13일(금) 4:30PM

2. 진행
    - 4개의 세션으로 나누어 진행
    - 팀 당 20~30분 소요
    - 중간상황을 보고하여 평가받고 자문의견을 받게됨
    - 평가 기준을 참고하여 준비할 것 

###### 좌장: 주용수, 평가위원: 최은미, 강승식, 한재일

<div style="background-color:transparent"><table border="1" cellpadding="0" cellspacing="0" dir="ltr" style="table-layout:fixed;font-size:10pt;font-family:arial,sans,sans-serif;width:0px;border-collapse:collapse;border:none"><colgroup><col width="39"><col width="154"><col width="58"><col width="348"></colgroup><tbody><tr style="height:21px"><td style="border:1px solid rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;font-weight:bold;text-align:center"><font color="#444444">팀</font></td><td style="border-top-width:1px;border-top-style:solid;border-top-color:rgb(0,0,0);border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;font-weight:bold;text-align:center"><font color="#444444">팀명</font></td><td style="border-top-width:1px;border-top-style:solid;border-top-color:rgb(0,0,0);border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;font-weight:bold;text-align:center"><font color="#444444">팀장</font></td><td style="border-top-width:1px;border-top-style:solid;border-top-color:rgb(0,0,0);border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-weight:bold;word-wrap:break-word;text-align:center"><font color="#444444">프로젝트 개요</font></td></tr><tr style="height:21px"><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);border-left-width:1px;border-left-style:solid;border-left-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;text-align:center"><font color="#444444">9</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial"><font color="#444444">VT</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;text-align:center"><font color="#444444">진예진</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;word-wrap:break-word"><font color="#444444">VISION THROUGH' 프로젝트는 스마트 미러와 스마트 행거를 융합한 IOT제품</font></td></tr><tr style="height:21px"><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);border-left-width:1px;border-left-style:solid;border-left-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;text-align:center"><font color="#444444">10</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial"><font color="#444444">국크다스</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;text-align:center"><font color="#444444">김종민</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;word-wrap:break-word"><font color="#444444">웹 사이트 형식이 기본이고 모바일에서도 간편하게 사용할 수 있게끔 안드로이드 어플리케이션</font></td></tr><tr style="height:21px"><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);border-left-width:1px;border-left-style:solid;border-left-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;text-align:center"><font color="#444444">11</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial"><font color="#444444">크로스</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;text-align:center"><font color="#444444">김세연</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;word-wrap:break-word"><font color="#444444">두 모바일 OS 어플리케이션을 C++로 개발하는 프레임워크</font></td></tr><tr style="height:21px"><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);border-left-width:1px;border-left-style:solid;border-left-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;text-align:center"><font color="#444444">13</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial"><font color="#444444">OMW (장애인보행서비스)</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;text-align:center"><font color="#444444">김수희</font></td><td style="border-right-width:1px;border-right-style:solid;border-right-color:rgb(0,0,0);border-bottom-width:1px;border-bottom-style:solid;border-bottom-color:rgb(0,0,0);overflow:hidden;padding:2px 3px;vertical-align:middle;font-family:Arial;word-wrap:break-word"><font color="#444444">시각장애인들 또는 어둠속의 보행자를 위한 장애물 감지 패션 서비스를 제공</font></td></tr></tbody></table></div>

**Comment by YEEN6** [comment]
문서를 모두 업로드하였으므로 이슈를 닫습니다.

**Comment by doeuncow** [comment]
발표 피피티 수정

https://goo.gl/xgdiQj

@YEEN6  @wlsdud  @daianaludice  확인해주세요~! 2. 시뮬레이션 추가해서 애니메이션 넣었어요~!
