### ISSUE TITLE
스마트 미러 하드웨어 제작

### ISSUE THREAD

**Issue by doeuncow** [kookmin-sw/2018-cap1-9#24]
스마트 미러 하드웨어 제작에 필요한 물품 및 규격 작성

**Comment by daianaludice** [comment]
![kakaotalk_20180407_214135323](https://user-images.githubusercontent.com/17774963/38463710-339c2582-3af0-11e8-804b-71d36a9d6340.jpg)

**Comment by doeuncow** [comment]
월요일 2시 : 유리 주문 및 미러필름 부착(@daianaludice  @me)
월요일 3시 : 머신샵에서 유리 프레임 제작 (@wlsdud @YEEN6 )

**Comment by doeuncow** [comment]
유리 = 높이 165cm*가로80cm*두께5mm

**Comment by doeuncow** [comment]
![kakaotalk_20180412_210148249](https://user-images.githubusercontent.com/30363239/39620388-f5507e5a-4fc5-11e8-9888-4c372b726d63.jpg)

**Comment by doeuncow** [comment]
원목 링크 (삼나무 각재, 1m짜리 6,500원)
http://www.mizwood.com/goods/view?no=1279
