### ISSUE TITLE
웹페이지 DB 연동 및 제어

### ISSUE THREAD

**Issue by daianaludice** [kookmin-sw/2018-cap1-9#36]
show_smart_mirror_screen, clothes_list, select_clothe 웹 페이지 DB와 연동
제어문,반복문,DB connect 등을 사용하여 PHP 페이지로 완성

**Comment by daianaludice** [comment]
html 파일 삭제 및 img 파일 그림 이름 변경, php파일 업데이트
및 DB연동과 제어.

**Comment by daianaludice** [comment]
사용자가 옷을 선택할 시 행거가 해당 옷을 찾아서 컨트롤 할 수 있도록 DB에 새로운 정보를 넣을 php페이지 생성

**Comment by daianaludice** [comment]
웹 페이지와 DB 연동 완료

**Comment by daianaludice** [comment]
DB 변동에 따른 DB연동 수정

**Comment by doeuncow** [comment]
https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/AmazonS3.html

아마존S3와 EC2 관련설명

**Comment by daianaludice** [comment]
연동 완료
