### ISSUE TITLE
물품 주문

### ISSUE THREAD

**Issue by doeuncow** [kookmin-sw/2018-cap1-9#8]
행거, 악세사리 회전 행거 주문

**Comment by daianaludice** [comment]
스마트미러 하드웨어 필요 물품 : 투명 유리 170cm*80cm*5mm 1개,하프미러필름 1개,필요할 경우 목재를 구매해야할 수 도 있다.

**Comment by wlsdud** [comment]
아두이노 우노 1개
아두이노 블루투스 모듈 2개
스텝모터 2개
서보모터 6개

**Comment by YEEN6** [comment]
#물품주문 링크 및 구매 개수 확인

##쿠팡

악세사리 회전행거 6개
[link to coupang](http://www.coupang.com/vp/products/14669678?vendorItemId=3095603990)

##MechaSolution
압력감지 전도성천 2개
[link to mechasolution](http://mechasolution.com/shop/goods/goods_view.php?&goodsno=1342)

아두이노 usb-A to usb-B cable
[Link to mechasolution]http://mechasolution.com/shop/goods/goods_view.php?&goodsno=544355

##ICbanq
서보모터 6개
[Link to ICbanq](http://www.icbanq.com/shop/product_detail.asp?prod_code=P007467736)

스텝모터 2개
[Link to ICbanq](http://www.icbanq.com/P008103003)

##Anymall
하프미러25 (1524mm*1M)
[Link to Anymall](http://www.any-mall.co.kr/shop/shopdetail.html?branduid=111053)

총 4개의 홈페이지에서 주문 할 예정이고, 아두이노 연결선이 없다는 의견을 받아들여 MechaSolution 홈페이지에서 같이 구매를 할 예정입니다.

@doeuncow @daianaludice @wlsdud 모두 한번씩 내역 ~점검~해주세요!

**Comment by YEEN6** [comment]
# 주문내역 및 배송예정일

물품명 |개수 | 가격합계 | 배송예정일
--------|------|-----------|--------------
하프미러필름 25 (1524mm*1M) | 1개 | 20,000원 | ?
악세사리 행거 | 6개 | 55,900원 | 3/26 (월)
압력감지형 전도성천 | 2개 | 하단가격에 포함 | ?
고속 USB2.0 A-B케이블 | 2개 | 15,040원 | ?
스텝모터 | 2개 | 158,400원 | ?
서보모터 | 6개 | 112,200원 | ?
. | 총계 | 361,540원 | .

**Comment by wlsdud** [comment]
스텝모터 드라이버 2개
http://motorbank.co.kr/product/%EB%93%9C%EB%9D%BC%EC%9D%B4%EB%B2%84-msd-224-2%EC%83%81-%EC%8A%A4%ED%85%8C%ED%95%91%EB%AA%A8%ED%84%B0-%EB%93%9C%EB%9D%BC%EC%9D%B4%EB%B2%84/5318/
점프선 각 1개
http://www.eduino.kr/product/detail.html?product_no=49&cate_no=71&display_group=1
http://www.eduino.kr/product/detail.html?product_no=342&cate_no=71&display_group=1
쿠킹호일
http://www.coupang.com/vp/products/6834091?itemId=30239802&vendorItemId=3044993895&q=%EC%BF%A0%ED%82%B9%ED%98%B8%EC%9D%BC&itemsCount=36&searchId=a358e3aebb2e497581011b53fba81093&rank=3
공구
http://www.coupang.com/vp/products/52798138?itemId=186102664&vendorItemId=3443179384&q=%EC%A0%84%EB%8F%99%EB%93%9C%EB%A6%B4&itemsCount=36&searchId=0a5641eca7054b3cb6bd47dd11654fc2&rank=13

**Comment by YEEN6** [comment]
배터리, 라즈베리파이 적외선 센서, 와이어스트리퍼, 배터리도 구매할거죠?
목록 쭉 써달라는 게 링크 안찾아놔도 뭐뭐 살지 쭉 적어달라는 얘기였어요~~
그리고 다음에 문서 작성할 땐 마크다운 써서 가독성 있게 해주세요!! 아니면 최소한 링크와 링크사이 띄어주세요.

**Comment by YEEN6** [comment]
## 2차 주문내역 및 배송일

물품명 | 개수 | 가격 | 배송비 | 합계 | 주문일(구입일) | 배송예정일 | 링크 | 비고
--------|-------|------|---------|------|------------------|--------------|-------|-----
스텝모터드라이버 | 2 | 69,850원 | 무료 | 139,700원 | - | - | [Motor bank](http://motorbank.co.kr/product/%EB%93%9C%EB%9D%BC%EC%9D%B4%EB%B2%84-msd-224-2%EC%83%81-%EC%8A%A4%ED%85%8C%ED%95%91%EB%AA%A8%ED%84%B0-%EB%93%9C%EB%9D%BC%EC%9D%B4%EB%B2%84/5318/) | -
암-암 점프선 20cm(40p) | 1 | 1,100원 | 2,500원 | 3,600원 | - | - | [Gmarket](http://item.gmarket.co.kr/Item?goodscode=701562809) | -
암-수 점프선 20cm(40p) | 1 | 1,100원 | 위와동일 | 1,100원 | - | - | 위와동일 | -
수-수 점프선 20cm(40p) | 1 | 1,100원 | 위와동일 | 1,100원 | - | - | 위와동일 | - 
쿠킹호일 | 1 | 3,000원 이내 | - | - | - | - | - | -오프라인 구매 예정
전동드릴 풀세트 | 1 | 28,900원 | - | 28,900원 | - | - | [coupang](http://www.coupang.com/vp/products/52798138?itemId=186102664&vendorItemId=3443179384&q=%EC%A0%84%EB%8F%99%EB%93%9C%EB%A6%B4&itemsCount=36&searchId=0a5641eca7054b3cb6bd47dd11654fc2&rank=13) | -
버니어 캘리퍼스 | 1 | 9,120원 | - | 9,120원 | - | - | [coupang](https://www.coupang.com/vp/products/1471970?itemId=6438278&vendorItemId=3008369058&q=%EB%B2%84%EB%8B%88%EC%96%B4+%EC%BA%98%EB%A6%AC%ED%8D%BC%EC%8A%A4&itemsCount=36&searchId=fba989c16d1c4a06acf861e52b21b93f&rank=2) | -



### 확인사항

@wlsdud 
- 쿠킹호일의 경우에는 제품가격과 배송비가 같으므로 직접 구매하는 것으로 하겠습니다.
- 점퍼선 구매처 바꿨습니다.
- 수-수 점퍼선(10cm)의 경우에는 이미 있는데 추가로 구매해야 하나요?
코멘트 달아주세요~


### 수령여부

- [ ] 스텝모터드라이버
- [ ] 암-암 점프선
- [ ] 암-수 점프선
- [ ] 수-수 점프선
- [ ]쿠킹호일
- [ ]전동드릴 풀세트
- [ ]버니어 캘리퍼스

**Comment by wlsdud** [comment]
다음에 올릴때는 가독성 있게할게
그리고 너가 말한 추가사항에서는 배터리빼고는 내가 좀더 공부를 하고나서 사도될거같아
배터리 추가해서 넣을게
그리고 암암 점프선은 필요없고 지금 가지고있는 점프선은 내가 알기로 다 브레드보드용이라 연장하면 쉽게 빠져서 수수 점프선을 따로 주문했어

**Comment by YEEN6** [comment]
넵 좋아여 암-암 빼고 일단 이렇게만 주문할게요~~
그론데 제가 다시 찾은 점프선이랑 오빠꺼랑 같은건가요??
그리구 저기는 수-수 점프선이 10센치인데 제가 찾은 건 20센치거든요. 10센치로 주문해야하나요?

**Comment by wlsdud** [comment]
암암빼고 저렇게 주문하면될거같아 10센치있으면 10센치로주문해줘

**Comment by YEEN6** [comment]
총 5개 물품 금일 주문완료했습니다. 물품 동아리방에서 수령한 사람은 수령여부에 체크 부탁해!
@doeuncow @daianaludice @wlsdud

**Comment by YEEN6** [comment]
@wlsdud 추가한 배터리랑 배터리 커넥터 주문했어요! 추가로 초음파센서랑 초음파센서 이용하기위한 저항도 구매했습니다.

**Comment by YEEN6** [comment]
부직포(검정) 2미터, 사포, 목재, 목장갑

**Comment by doeuncow** [comment]
목재 구매 사이트
http://www.mizwood.com/goods/view?no=2295

**Comment by YEEN6** [comment]
목재 변경
삼나무각재
http://www.mizwood.com/goods/view?no=1279

1180 * 2개
2350 * 2개

총액 44,400원 + 배송비 별도

**Comment by YEEN6** [comment]
현재까지 사용한 지원비 내역입니다.

[CLICK](https://docs.google.com/spreadsheets/d/1D4cMwBDVlw9O5JdxwbbybUv-vx-HwQvV2QbV9iQ-WWQ/edit?usp=sharing)
